service: gilead-ra-api-app

provider:
 name: aws
 runtime: nodejs14.x
 memorySize: 128
 timeout: 10
 stage: dev
 region: ap-south-1

functions:
 api:
   handler: lambda.universal
   events:
     - http: 
        path: /
        method: ANY
        cors: true
     - http: 
         path: /{proxy+}
         method: ANY
         cors: true